### ISSUE TITLE
req.seneca.actAsync is not a function

### ISSUE THREAD

**Issue by marcoreni** [hapijs/chairo#69]
Hello,

I'm trying to migrate to Chairo v4 (Hapi v17), but I'm encountering some issues.

I tried declaring a route as:
```javascript
{
  method: 'GET',
  path: '/test',
  config: {
    handler: (req, h) => {
      return h.act(Object.assign({}, req.query, {
        role: 'test.role',
        cmd: 'test.cmd',
      }));
    }
  }
}
```

But when I call the route I'm getting:
```
Debug: internal, implementation, error
    TypeError: this.request.seneca.actAsync is not a function
    at internals.Toolkit.internals.toolkit.act (/usr/src/app/node_modules/chairo/lib/index.js:153:32)
    at handler (/usr/src/app/src/routes/test.js:9:9)
    at module.exports.internals.Manager.execute (/usr/src/app/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/usr/src/app/node_modules/hapi/lib/handler.js:52:48)
    at exports.execute (/usr/src/app/node_modules/hapi/lib/handler.js:37:36)
    at module.exports.internals.Request._lifecycle (/usr/src/app/node_modules/hapi/lib/request.js:261:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Same thing happens when I use:
```javascript
// [...]
handler: (req, h) => {
      return req.seneca.actAsync(Object.assign({}, req.query, {
        role: 'test.role',
        cmd: 'test.cmd',
      }));
    }
```
==> 
```
Debug: internal, implementation, error
    TypeError: req.seneca.actAsync is not a function
    at handler (/usr/src/app/src/routes/test.js:9:25)
    at module.exports.internals.Manager.execute (/usr/src/app/node_modules/hapi/lib/toolkit.js:35:106)
    at Object.internals.handler (/usr/src/app/node_modules/hapi/lib/handler.js:52:48)
    at exports.execute (/usr/src/app/node_modules/hapi/lib/handler.js:37:36)
    at module.exports.internals.Request._lifecycle (/usr/src/app/node_modules/hapi/lib/request.js:261:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
What am I missing?

**Comment by ErickWendel** [comment]
I trying to reproduce that issue, Do you have an example running ?

**Comment by marcoreni** [comment]
https://gist.github.com/marcoreni/f36c64bef5c82222a9a1297005954fbf

After further testing I verified that the error shows if I insert seneca object as an option during plugin registration.
